services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.dev
    volumes:
      - ./apps/api/src:/app/apps/api/src
      - ./packages/types/src:/app/packages/types/src
    environment:
      - NODE_ENV=development
