shellEmulator: true

trustPolicy: trust-all

packages:
  - apps/*
  - packages/*
allowBuilds:
  citation-js: true
  esbuild: true
  protobufjs: true
  simple-git-hooks: true
  spawn-sync: true
  vue-demi: true
