/* tslint:disable */
/* eslint-disable */
/**
 * Europe PMC Articles RESTful API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArticleInput
 */
export interface ArticleInput {
    /**
     * 
     * @type {string}
     * @memberof ArticleInput
     */
    src?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleInput
     */
    extId?: string;
}

/**
 * Check if a given object implements the ArticleInput interface.
 */
export function instanceOfArticleInput(value: object): value is ArticleInput {
    return true;
}

export function ArticleInputFromJSON(json: any): ArticleInput {
    return ArticleInputFromJSONTyped(json, false);
}

export function ArticleInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleInput {
    if (json == null) {
        return json;
    }
    return {
        
        'src': json['src'] == null ? undefined : json['src'],
        'extId': json['extId'] == null ? undefined : json['extId'],
    };
}

export function ArticleInputToJSON(json: any): ArticleInput {
    return ArticleInputToJSONTyped(json, false);
}

export function ArticleInputToJSONTyped(value?: ArticleInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'src': value['src'],
        'extId': value['extId'],
    };
}

