apiVersion: 1

contactPoints:
  - name: Email Alert
    receivers:
      - uid: email-contact
        type: email
        settings:
          addresses: contact@jeffnawroth.me
        disableResolveMessage: false

policies:
  - receiver: Email Alert
    group_by: [alertname, severity]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
