/* tslint:disable */
/* eslint-disable */
/**
 * Academic Graph API
 * Fetch paper and author data from the Semantic Scholar Academic Graph (S2AG).         <br><br>         Some things to note:         <ul>         <li>If you are using an API key, it must be set in the header <code>x-api-key</code> (case-sensitive).</li>         <li>We have two different IDs for a single paper:           <ul>             <li><code>paperId</code> - string - The primary way to identify papers when using our website or this API</li>             <li><code>corpusId</code> - int64 - A second way to identify papers. Our datasets use corpusId when pointing to papers.</li>           </ul>         </li>         <li>Other useful resources<ul>         <li><a href=\"https://www.semanticscholar.org/product/api\">Overview</a></li>         <li><a href=\"https://github.com/allenai/s2-folks/\">allenai/s2-folks</a></li>         <li><a href=\"https://github.com/allenai/s2-folks/blob/main/FAQ.md\">FAQ</a> in allenai/s2folks</li>         </ul></li>         
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BasePaper } from './BasePaper';
import {
    BasePaperFromJSON,
    BasePaperFromJSONTyped,
    BasePaperToJSON,
    BasePaperToJSONTyped,
} from './BasePaper';

/**
 * 
 * @export
 * @interface AuthorWithPapers
 */
export interface AuthorWithPapers {
    /**
     * Semantic Scholar’s unique ID for the author.
     * @type {string}
     * @memberof AuthorWithPapers
     */
    authorId?: string;
    /**
     * An object that contains the ORCID/DBLP IDs for the author, if known.
     * @type {object}
     * @memberof AuthorWithPapers
     */
    externalIds?: object;
    /**
     * URL of the author on the Semantic Scholar website.
     * @type {string}
     * @memberof AuthorWithPapers
     */
    url?: string;
    /**
     * Author’s name.
     * @type {string}
     * @memberof AuthorWithPapers
     */
    name?: string;
    /**
     * Array of organizational affiliations for the author.
     * @type {Array<string>}
     * @memberof AuthorWithPapers
     */
    affiliations?: Array<string>;
    /**
     * The author’s homepage.
     * @type {string}
     * @memberof AuthorWithPapers
     */
    homepage?: string;
    /**
     * The author's total publications count.
     * @type {string}
     * @memberof AuthorWithPapers
     */
    paperCount?: string;
    /**
     * The author's total citations count.
     * @type {string}
     * @memberof AuthorWithPapers
     */
    citationCount?: string;
    /**
     * The author’s h-index, which is a measure of the productivity and citation impact of the author’s publications: https://www.semanticscholar.org/faq#h-index
     * @type {string}
     * @memberof AuthorWithPapers
     */
    hIndex?: string;
    /**
     * 
     * @type {Array<BasePaper>}
     * @memberof AuthorWithPapers
     */
    papers?: Array<BasePaper>;
}

/**
 * Check if a given object implements the AuthorWithPapers interface.
 */
export function instanceOfAuthorWithPapers(value: object): value is AuthorWithPapers {
    return true;
}

export function AuthorWithPapersFromJSON(json: any): AuthorWithPapers {
    return AuthorWithPapersFromJSONTyped(json, false);
}

export function AuthorWithPapersFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorWithPapers {
    if (json == null) {
        return json;
    }
    return {
        
        'authorId': json['authorId'] == null ? undefined : json['authorId'],
        'externalIds': json['externalIds'] == null ? undefined : json['externalIds'],
        'url': json['url'] == null ? undefined : json['url'],
        'name': json['name'] == null ? undefined : json['name'],
        'affiliations': json['affiliations'] == null ? undefined : json['affiliations'],
        'homepage': json['homepage'] == null ? undefined : json['homepage'],
        'paperCount': json['paperCount'] == null ? undefined : json['paperCount'],
        'citationCount': json['citationCount'] == null ? undefined : json['citationCount'],
        'hIndex': json['hIndex'] == null ? undefined : json['hIndex'],
        'papers': json['papers'] == null ? undefined : ((json['papers'] as Array<any>).map(BasePaperFromJSON)),
    };
}

export function AuthorWithPapersToJSON(json: any): AuthorWithPapers {
    return AuthorWithPapersToJSONTyped(json, false);
}

export function AuthorWithPapersToJSONTyped(value?: AuthorWithPapers | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authorId': value['authorId'],
        'externalIds': value['externalIds'],
        'url': value['url'],
        'name': value['name'],
        'affiliations': value['affiliations'],
        'homepage': value['homepage'],
        'paperCount': value['paperCount'],
        'citationCount': value['citationCount'],
        'hIndex': value['hIndex'],
        'papers': value['papers'] == null ? undefined : ((value['papers'] as Array<any>).map(BasePaperToJSON)),
    };
}

