/* tslint:disable */
/* eslint-disable */
/**
 * Academic Graph API
 * Fetch paper and author data from the Semantic Scholar Academic Graph (S2AG).         <br><br>         Some things to note:         <ul>         <li>If you are using an API key, it must be set in the header <code>x-api-key</code> (case-sensitive).</li>         <li>We have two different IDs for a single paper:           <ul>             <li><code>paperId</code> - string - The primary way to identify papers when using our website or this API</li>             <li><code>corpusId</code> - int64 - A second way to identify papers. Our datasets use corpusId when pointing to papers.</li>           </ul>         </li>         <li>Other useful resources<ul>         <li><a href=\"https://www.semanticscholar.org/product/api\">Overview</a></li>         <li><a href=\"https://github.com/allenai/s2-folks/\">allenai/s2-folks</a></li>         <li><a href=\"https://github.com/allenai/s2-folks/blob/main/FAQ.md\">FAQ</a> in allenai/s2folks</li>         </ul></li>         
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Autocomplete Paper
 */
export interface AutocompletePaper {
    /**
     * The paper's primary unique identifier.
     * @type {string}
     * @memberof Autocomplete Paper
     */
    id?: string;
    /**
     * Title of the paper.
     * @type {string}
     * @memberof Autocomplete Paper
     */
    title?: string;
    /**
     * Summary of the authors of the paper and year of publication.
     * @type {string}
     * @memberof Autocomplete Paper
     */
    authorsYear?: string;
}

/**
 * Check if a given object implements the Autocomplete Paper interface.
 */
export function instanceOfAutocompletePaper(value: object): value is AutocompletePaper {
    return true;
}

export function AutocompletePaperFromJSON(json: any): AutocompletePaper {
    return AutocompletePaperFromJSONTyped(json, false);
}

export function AutocompletePaperFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutocompletePaper {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'authorsYear': json['authorsYear'] == null ? undefined : json['authorsYear'],
    };
}

export function AutocompletePaperToJSON(json: any): AutocompletePaper {
    return AutocompletePaperToJSONTyped(json, false);
}

export function AutocompletePaperToJSONTyped(value?: AutocompletePaper | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'authorsYear': value['authorsYear'],
    };
}

