/* tslint:disable */
/* eslint-disable */
/**
 * Academic Graph API
 * Fetch paper and author data from the Semantic Scholar Academic Graph (S2AG).         <br><br>         Some things to note:         <ul>         <li>If you are using an API key, it must be set in the header <code>x-api-key</code> (case-sensitive).</li>         <li>We have two different IDs for a single paper:           <ul>             <li><code>paperId</code> - string - The primary way to identify papers when using our website or this API</li>             <li><code>corpusId</code> - int64 - A second way to identify papers. Our datasets use corpusId when pointing to papers.</li>           </ul>         </li>         <li>Other useful resources<ul>         <li><a href=\"https://www.semanticscholar.org/product/api\">Overview</a></li>         <li><a href=\"https://github.com/allenai/s2-folks/\">allenai/s2-folks</a></li>         <li><a href=\"https://github.com/allenai/s2-folks/blob/main/FAQ.md\">FAQ</a> in allenai/s2folks</li>         </ul></li>         
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Reference } from './Reference';
import {
    ReferenceFromJSON,
    ReferenceFromJSONTyped,
    ReferenceToJSON,
    ReferenceToJSONTyped,
} from './Reference';

/**
 * 
 * @export
 * @interface ReferenceBatch
 */
export interface ReferenceBatch {
    /**
     * Starting position for this batch.
     * @type {number}
     * @memberof ReferenceBatch
     */
    offset?: number;
    /**
     * Starting position of the next batch. Absent if no more data exists.
     * @type {number}
     * @memberof ReferenceBatch
     */
    next?: number;
    /**
     * 
     * @type {Array<Reference>}
     * @memberof ReferenceBatch
     */
    data?: Array<Reference>;
}

/**
 * Check if a given object implements the ReferenceBatch interface.
 */
export function instanceOfReferenceBatch(value: object): value is ReferenceBatch {
    return true;
}

export function ReferenceBatchFromJSON(json: any): ReferenceBatch {
    return ReferenceBatchFromJSONTyped(json, false);
}

export function ReferenceBatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferenceBatch {
    if (json == null) {
        return json;
    }
    return {
        
        'offset': json['offset'] == null ? undefined : json['offset'],
        'next': json['next'] == null ? undefined : json['next'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ReferenceFromJSON)),
    };
}

export function ReferenceBatchToJSON(json: any): ReferenceBatch {
    return ReferenceBatchToJSONTyped(json, false);
}

export function ReferenceBatchToJSONTyped(value?: ReferenceBatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'offset': value['offset'],
        'next': value['next'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ReferenceToJSON)),
    };
}

