/* tslint:disable */
/* eslint-disable */
/**
 * Academic Graph API
 * Fetch paper and author data from the Semantic Scholar Academic Graph (S2AG).         <br><br>         Some things to note:         <ul>         <li>If you are using an API key, it must be set in the header <code>x-api-key</code> (case-sensitive).</li>         <li>We have two different IDs for a single paper:           <ul>             <li><code>paperId</code> - string - The primary way to identify papers when using our website or this API</li>             <li><code>corpusId</code> - int64 - A second way to identify papers. Our datasets use corpusId when pointing to papers.</li>           </ul>         </li>         <li>Other useful resources<ul>         <li><a href=\"https://www.semanticscholar.org/product/api\">Overview</a></li>         <li><a href=\"https://github.com/allenai/s2-folks/\">allenai/s2-folks</a></li>         <li><a href=\"https://github.com/allenai/s2-folks/blob/main/FAQ.md\">FAQ</a> in allenai/s2folks</li>         </ul></li>         
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OpenAccessInfo } from './OpenAccessInfo';
import {
    OpenAccessInfoFromJSON,
    OpenAccessInfoFromJSONTyped,
    OpenAccessInfoToJSON,
    OpenAccessInfoToJSONTyped,
} from './OpenAccessInfo';

/**
 * 
 * @export
 * @interface Paper
 */
export interface Paper {
    /**
     * Semantic Scholar’s secondary unique identifier for a paper.
     * @type {string}
     * @memberof Paper
     */
    corpusId?: string;
    /**
     * Title of the paper.
     * @type {string}
     * @memberof Paper
     */
    title?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Paper
     */
    authors?: Array<string>;
    /**
     * 
     * @type {OpenAccessInfo}
     * @memberof Paper
     */
    openAccessInfo?: OpenAccessInfo;
}

/**
 * Check if a given object implements the Paper interface.
 */
export function instanceOfPaper(value: object): value is Paper {
    return true;
}

export function PaperFromJSON(json: any): Paper {
    return PaperFromJSONTyped(json, false);
}

export function PaperFromJSONTyped(json: any, ignoreDiscriminator: boolean): Paper {
    if (json == null) {
        return json;
    }
    return {
        
        'corpusId': json['corpusId'] == null ? undefined : json['corpusId'],
        'title': json['title'] == null ? undefined : json['title'],
        'authors': json['authors'] == null ? undefined : json['authors'],
        'openAccessInfo': json['openAccessInfo'] == null ? undefined : OpenAccessInfoFromJSON(json['openAccessInfo']),
    };
}

export function PaperToJSON(json: any): Paper {
    return PaperToJSONTyped(json, false);
}

export function PaperToJSONTyped(value?: Paper | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'corpusId': value['corpusId'],
        'title': value['title'],
        'authors': value['authors'],
        'openAccessInfo': OpenAccessInfoToJSON(value['openAccessInfo']),
    };
}

