/* tslint:disable */
/* eslint-disable */
/**
 * Academic Graph API
 * Fetch paper and author data from the Semantic Scholar Academic Graph (S2AG).         <br><br>         Some things to note:         <ul>         <li>If you are using an API key, it must be set in the header <code>x-api-key</code> (case-sensitive).</li>         <li>We have two different IDs for a single paper:           <ul>             <li><code>paperId</code> - string - The primary way to identify papers when using our website or this API</li>             <li><code>corpusId</code> - int64 - A second way to identify papers. Our datasets use corpusId when pointing to papers.</li>           </ul>         </li>         <li>Other useful resources<ul>         <li><a href=\"https://www.semanticscholar.org/product/api\">Overview</a></li>         <li><a href=\"https://github.com/allenai/s2-folks/\">allenai/s2-folks</a></li>         <li><a href=\"https://github.com/allenai/s2-folks/blob/main/FAQ.md\">FAQ</a> in allenai/s2folks</li>         </ul></li>         
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Citation } from './Citation';
import {
    CitationFromJSON,
    CitationFromJSONTyped,
    CitationToJSON,
    CitationToJSONTyped,
} from './Citation';

/**
 * 
 * @export
 * @interface CitationBatch
 */
export interface CitationBatch {
    /**
     * Starting position for this batch.
     * @type {number}
     * @memberof CitationBatch
     */
    offset?: number;
    /**
     * Starting position of the next batch. Absent if no more data exists.
     * @type {number}
     * @memberof CitationBatch
     */
    next?: number;
    /**
     * 
     * @type {Array<Citation>}
     * @memberof CitationBatch
     */
    data?: Array<Citation>;
}

/**
 * Check if a given object implements the CitationBatch interface.
 */
export function instanceOfCitationBatch(value: object): value is CitationBatch {
    return true;
}

export function CitationBatchFromJSON(json: any): CitationBatch {
    return CitationBatchFromJSONTyped(json, false);
}

export function CitationBatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): CitationBatch {
    if (json == null) {
        return json;
    }
    return {
        
        'offset': json['offset'] == null ? undefined : json['offset'],
        'next': json['next'] == null ? undefined : json['next'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(CitationFromJSON)),
    };
}

export function CitationBatchToJSON(json: any): CitationBatch {
    return CitationBatchToJSONTyped(json, false);
}

export function CitationBatchToJSONTyped(value?: CitationBatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'offset': value['offset'],
        'next': value['next'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(CitationToJSON)),
    };
}

