/* tslint:disable */
/* eslint-disable */
/**
 * Academic Graph API
 * Fetch paper and author data from the Semantic Scholar Academic Graph (S2AG).         <br><br>         Some things to note:         <ul>         <li>If you are using an API key, it must be set in the header <code>x-api-key</code> (case-sensitive).</li>         <li>We have two different IDs for a single paper:           <ul>             <li><code>paperId</code> - string - The primary way to identify papers when using our website or this API</li>             <li><code>corpusId</code> - int64 - A second way to identify papers. Our datasets use corpusId when pointing to papers.</li>           </ul>         </li>         <li>Other useful resources<ul>         <li><a href=\"https://www.semanticscholar.org/product/api\">Overview</a></li>         <li><a href=\"https://github.com/allenai/s2-folks/\">allenai/s2-folks</a></li>         <li><a href=\"https://github.com/allenai/s2-folks/blob/main/FAQ.md\">FAQ</a> in allenai/s2folks</li>         </ul></li>         
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Annotations } from './Annotations';
import {
    AnnotationsFromJSON,
    AnnotationsFromJSONTyped,
    AnnotationsToJSON,
    AnnotationsToJSONTyped,
} from './Annotations';

/**
 * 
 * @export
 * @interface Snippet
 */
export interface Snippet {
    /**
     * The direct quote or snippet from the paper relevant to the query.
     * @type {string}
     * @memberof Snippet
     */
    text?: string;
    /**
     * Where the snippet is located, options are: title, abstract, or body. 
     * @type {string}
     * @memberof Snippet
     */
    snippetKind?: string;
    /**
     * Only applies to snippets from the body, refers to the section of the paper where the snippet is located.
     * @type {string}
     * @memberof Snippet
     */
    section?: string;
    /**
     * The location of the snippet within the paper.
     * @type {object}
     * @memberof Snippet
     */
    snippetOffset?: object;
    /**
     * 
     * @type {Annotations}
     * @memberof Snippet
     */
    annotations?: Annotations;
}

/**
 * Check if a given object implements the Snippet interface.
 */
export function instanceOfSnippet(value: object): value is Snippet {
    return true;
}

export function SnippetFromJSON(json: any): Snippet {
    return SnippetFromJSONTyped(json, false);
}

export function SnippetFromJSONTyped(json: any, ignoreDiscriminator: boolean): Snippet {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'] == null ? undefined : json['text'],
        'snippetKind': json['snippetKind'] == null ? undefined : json['snippetKind'],
        'section': json['section'] == null ? undefined : json['section'],
        'snippetOffset': json['snippetOffset'] == null ? undefined : json['snippetOffset'],
        'annotations': json['annotations'] == null ? undefined : AnnotationsFromJSON(json['annotations']),
    };
}

export function SnippetToJSON(json: any): Snippet {
    return SnippetToJSONTyped(json, false);
}

export function SnippetToJSONTyped(value?: Snippet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'snippetKind': value['snippetKind'],
        'section': value['section'],
        'snippetOffset': value['snippetOffset'],
        'annotations': AnnotationsToJSON(value['annotations']),
    };
}

