/* tslint:disable */
/* eslint-disable */
/**
 * Academic Graph API
 * Fetch paper and author data from the Semantic Scholar Academic Graph (S2AG).         <br><br>         Some things to note:         <ul>         <li>If you are using an API key, it must be set in the header <code>x-api-key</code> (case-sensitive).</li>         <li>We have two different IDs for a single paper:           <ul>             <li><code>paperId</code> - string - The primary way to identify papers when using our website or this API</li>             <li><code>corpusId</code> - int64 - A second way to identify papers. Our datasets use corpusId when pointing to papers.</li>           </ul>         </li>         <li>Other useful resources<ul>         <li><a href=\"https://www.semanticscholar.org/product/api\">Overview</a></li>         <li><a href=\"https://github.com/allenai/s2-folks/\">allenai/s2-folks</a></li>         <li><a href=\"https://github.com/allenai/s2-folks/blob/main/FAQ.md\">FAQ</a> in allenai/s2folks</li>         </ul></li>         
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Tldr
 */
export interface Tldr {
    /**
     * The tldr model version number: https://github.com/allenai/scitldr
     * @type {string}
     * @memberof Tldr
     */
    model?: string;
    /**
     * The tldr paper summary.
     * @type {string}
     * @memberof Tldr
     */
    text?: string;
}

/**
 * Check if a given object implements the Tldr interface.
 */
export function instanceOfTldr(value: object): value is Tldr {
    return true;
}

export function TldrFromJSON(json: any): Tldr {
    return TldrFromJSONTyped(json, false);
}

export function TldrFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tldr {
    if (json == null) {
        return json;
    }
    return {
        
        'model': json['model'] == null ? undefined : json['model'],
        'text': json['text'] == null ? undefined : json['text'],
    };
}

export function TldrToJSON(json: any): Tldr {
    return TldrToJSONTyped(json, false);
}

export function TldrToJSONTyped(value?: Tldr | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'model': value['model'],
        'text': value['text'],
    };
}

