FROM node:22-bookworm-slim
ENV NODE_ENV=development
WORKDIR /app
RUN corepack enable
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.json ./
COPY apps/api/tsconfig.json apps/api/
COPY apps/api/package.json apps/api/
COPY packages/types/package.json packages/types/
COPY packages/types/tsconfig.json packages/types/
COPY packages/eslint-config/package.json packages/eslint-config/
RUN --mount=type=cache,id=pnpm,target=/root/.local/share/pnpm/store pnpm install --no-frozen-lockfile
COPY packages/types/ packages/types/
RUN pnpm --filter @source-taster/types build
COPY apps/api/ apps/api/
EXPOSE 8000
CMD ["pnpm", "--filter", "@source-taster/api", "dev"]
